if else file moving

diff --git a/.github/workflows/create-examples.yml b/.github/workflows/create-examples.yml
--- a/.github/workflows/create-examples.yml
+++ b/.github/workflows/create-examples.yml
@@ -28,7 +28,12 @@ jobs:
           asreview makita template arfi -s ./examples/data -p ./examples/arfi_example --overwrite --platform linux
           asreview makita template basic -s ./examples/data -p ./examples/basic_example --overwrite --platform linux
           asreview makita template multimodel -s ./examples/data -p ./examples/multimodel_example --overwrite --platform linux
-          mv ./examples/data/Smid_2020.csv prior_Smid_2020.csv
+          if [ -f ./examples/data/Smid_2020.csv ]; then
+            mv ./examples/data/Smid_2020.csv prior_Smid_2020.csv
+          else
+            echo "File Smid_2020.csv not found in ./examples/data/"
+            exit 1
+          fi
           asreview makita template prior -s ./examples/data -p ./examples/prior_example --overwrite --platform linux
 
       # Clean up data files (e.g., CSV, XLSX) to avoid committing them
